#!/bin/sh
mvn clean package && docker build -t 22012/ExamClient .
docker rm -f ExamClient 2>/dev/null || true && docker run -it --name ExamClient -p 8080:8080 -p 4848:4848 -p 8181:8181 --name ExamClient 22012/ExamClient
