#!/bin/sh
mvn clean package && docker build -t 22012/ExamEmployee .
docker rm -f ExamEmployee 2>/dev/null || true && docker run -it --name ExamEmployee -p 8080:8080 -p 4848:4848 -p 8181:8181 --name ExamEmployee 22012/ExamEmployee
