#!/bin/sh
#deploy="false"
deploy="true"

image=ExamEmployee
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t 22012/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push 22012/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag 22012/${image}:1.0-SNAPSHOT 22012/${image}:latest
        docker push 22012/${image}:latest
    fi
fi